addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.9.11")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.5.1")
addSbtPlugin("com.github.ghostdogpr" % "caliban-codegen-sbt" % "1.2.1")
